# Generated by Django 4.1.4 on 2023-11-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(blank=True, choices=[('INFLUENCER', 'INFLUENCER'), ('BRAND', 'BRAND'), ('COMPANY', 'COMPANY')], max_length=15, null=True),
        ),
    ]
