# Generated by Django 4.1.4 on 2023-11-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Birthday'),
        ),
        migrations.AddField(
            model_name='influencer',
            name='facebook_handle',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='instagram_handle',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='mobile',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='tiktok_handle',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
